# Generated by Django 4.1.5 on 2023-01-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_foods_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='time_duration',
            field=models.FloatField(),
        ),
    ]
